name: Analyze Bicep Modules
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  analyze_arm:
    name: Analyze templates
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v3

      - name: 📈 Analyze Azure template files
        uses: microsoft/ps-rule@v2.7.0
        with:
          modules: 'PSRule.Rules.Azure'
          option: ps-rule.yaml
          outputFormat: Sarif
          outputPath: reports/ps-rule-results.sarif

      - name: ⬆️ Upload results to security tab
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: reports/ps-rule-results.sarif
