# name: Login
# on:
#   push:
#     branches: ["main"]
#   pull_request:
#     branches: ["main"]
#   workflow_dispatch:
# jobs:
#   job:
#     name: Login
#     runs-on: ubuntu-latest
#     steps:
#       - name: Login via Az module
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}
#           enable-AzPSSession: true
