name: Azure Update Management

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
    paths:
      - "Azure Update Management/*"
  pull_request:
    branches: [master]
    paths:
      - "Azure Update Management/*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  solution: upd
  company: "hob"
  shortregion: "we"
  environment: "p"
  sequence: "01"
  costcenter: "HOB90001"
  ownerEmail: "email@hob.hob"
  department: "Hob IT"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  BuildIaC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.azure }}
          enable-AzPSSession: true

      - name: Create Resource Group
        uses: azure/powershell@v1
        with:
          inlineScript: New-AzResourceGroup -Name rg-${{ env.shortregion }}-${{ env.company }}-${{ env.solution }}-${{ env.environment }}-${{ env.sequence }} -Location WestEurope -Force
          azPSVersion: "latest"

      - name: Test Azure Update Management Infrastructure
        uses: azure/powershell@v1
        with:
          inlineScript: Test-AzDeployment -TemplateFile "Azure Update Management/main.bicep" -solution ${{ env.solution }} -environment ${{ env.environment }} -Location WestEurope
          azPSVersion: "latest"

  PreviewIaC:
    needs: [BuildIaC]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.azure }}
          enable-AzPSSession: true

      - name: Preview Azure Update Management Infrastructure
        uses: azure/powershell@v1
        with:
          inlineScript: New-AzDeployment -WhatIf -TemplateFile "Azure Update Management/main.bicep" -solution ${{ env.solution }} -environment ${{ env.environment }} -Location WestEurope
          azPSVersion: "latest"

  DeployIaC:
    needs: [BuildIaC, PreviewIaC]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.azure }}
          enable-AzPSSession: true

      - name: Deploy Azure Update Management Infrastructure
        uses: azure/powershell@v1
        with:
          inlineScript: New-AzDeployment -Name bicep-${{ env.GITHUB_RUN_ID }} -TemplateFile "Azure Update Management/main.bicep" -solution ${{ env.solution }} -environment ${{ env.environment }} -Location WestEurope
          azPSVersion: "latest"
