name: shared-components

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - '_modules/mod-vnet.bicep'
      - '_modules/mod-loganalytics.bicep'
      - 'Virtual Network/*'
  pull_request:
    branches: [ master ]
    paths:
      - '_modules/mod-vnet.bicep'
      - 'Virtual Network/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  solution: aib 
  company: 'hob'
  shortregion: 'we'
  environment: 'p'
  sequence: '01'
  costcenter: 'HOB90001'
  ownerEmail: 'email@hob.hob'
  department: 'Hob IT'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  OpsDeploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.azure }}
          enable-AzPSSession: true
          
      - name: Create Resource Group
        uses: azure/powershell@v1
        with:
          inlineScript: New-AzResourceGroup -Name shared -Location WestEurope -Force
          azPSVersion: 'latest'

      - name: Deploy VNET
        uses: azure/powershell@v1
        with:
          inlineScript: New-AzResourceGroupDeployment -Name shared-vnet -ResourceGroupName shared -TemplateFile "_modules/mod-vnet.bicep" -TemplateParameterFile "Virtual Network/parameters/vnet.parameters.json"
          azPSVersion: 'latest'

      - name: Deploy LAW
        uses: azure/powershell@v1
        with:
          inlineScript: New-AzResourceGroupDeployment -Name shared-law -ResourceGroupName shared -TemplateFile "_modules/mod-loganalytics.bicep" -logAnalyticsWorkspaceName 'shared-law'
          azPSVersion: 'latest'

      - name: Deploy LAW
        uses: azure/powershell@v1
        with:
          inlineScript: New-AzResourceGroupDeployment -Name shared-kv -ResourceGroupName shared -TemplateFile "_modules/mod-keyvault.bicep" -keyVaultName 'shared-keyvault' -defaultAction 'Allow'
          azPSVersion: 'latest'
      
      
