# This is a basic workflow to help you get started with Actions

name: PSF-Azure-Function

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  solution: psf 
  company: 'hob'
  shortregion: 'we'
  environment: 'p'
  sequence: '01'
  costcenter: 'HOB90001'
  ownerEmail: 'email@hob.hob'
  department: 'Hob IT'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  OpsDeploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.azure }}
          enable-AzPSSession: true
          
      - name: Create Resource Group
        uses: azure/powershell@v1
        with:
          inlineScript: New-AzResourceGroup -Name rg-${{ env.shortregion }}-${{ env.company }}-${{ env.solution }}-${{ env.environment }}-${{ env.sequence }} -Location WestEurope -Force
          azPSVersion: 'latest'

      - name: Deploy solution infrastructure
        uses: azure/powershell@v1
        with:
          inlineScript: New-AzDeployment -TemplateFile "PowerShell Function App/main.bicep" -solution ${{ env.solution }} -environment ${{ env.environment }} -Location WestEurope
          azPSVersion: 'latest'
    
  DevDeploy:
    runs-on: ubuntu-latest
    steps:
      steps:
        - name: Get WebApp/FunctionApp publish profile
          id: webapp
          uses: aliencube/publish-profile-actions@v1
          env:
            AZURE_CREDENTIALS: ${{ secrets.azure }}
          with:
            resourceGroupName: rg-${{ env.shortregion }}-${{ env.company }}-${{ env.solution }}-${{ env.environment }}-${{ env.sequence }}
            appName: fca-${{ env.shortregion }}-${{ env.company }}-${{ env.solution }}-${{ env.environment }}-${{ env.sequence }}
        
        - name: 'Run Azure Functions Action'
          uses: Azure/functions-action@v1
          id: fa
          with:
            app-name: fca-${{ env.shortregion }}-${{ env.company }}-${{ env.solution }}-${{ env.environment }}-${{ env.sequence }}
            package: "PowerShell Function App/src"
            publish-profile: ${{ steps.webapp.outputs.profile }}
        
      
